### ISSUE TITLE
Game not work

### ISSUE THREAD

**Issue by Bexpg-0** [AlanMWalker/PlanetThing#35]
Game not working why?

**Comment by Bexpg-0** [comment]
Can you share picture from game i really interest it looks good game.

**Comment by AlanMWalker** [comment]
Erm, what?

**Comment by Bexpg-0** [comment]
> Erm, what?

I open exe and not worked

**Comment by AlanMWalker** [comment]
I think I'll need a bit more info, which exe? Did you grab it from releases? Also why, I don't remember ever having publically shared anything of this game other than to friends...

**Comment by Bexpg-0** [comment]
> I think I'll need a bit more info, which exe? Did you grab it from releases? Also why, I don't remember ever having publically shared anything of this game other than to friends...

I open exe in release and not worked

**Comment by Bexpg-0** [comment]
i got black screen
